apiVersion: batch/v1
kind: Job
metadata:
  name: icp-cloudant-backup
spec:
  template:
    spec:
      volumes:
      - name: cloudant-backup
        persistentVolumeClaim:
          claimName: cloudant-backup
      containers:
      - name: icp-cloudant-backup
        image: "patrocinio/icp-backup-cloudant-backup:latest"
        command: ["/cloudant-backup.sh"]
        volumeMounts:
          - mountPath: "/backups"
            name: cloudant-backup
      restartPolicy: Never
  backoffLimit: 3
