apiVersion: batch/v1
kind: Job
metadata:
  name: icp-cloudant-restore
spec:
  template:
    spec:
      volumes:
      - name: cloudant-backup
        persistentVolumeClaim:
          claimName: cloudant-backup
      containers:
      - name: icp-cloudant-restore
        image: "patrocinio/icp-backup-cloudant-backup:latest"
        env:
        - name: DBNAME
          valueFrom:
            configMapKeyRef:
              name: cloudant-dbs
              key: dbnames
        command: ["/cloudant-restore.sh"]
        args: ["--dbnames", "$(DBNAME)"]
        volumeMounts:
          - mountPath: "/backups"
            name: cloudant-backup
      restartPolicy: Never
  backoffLimit: 3
