{{- if and ( .Values.persistence.enabled ) (not .Values.persistence.pvc_exists) }}
# Backup PVC template
# Picked up the start for this template here:
#   https://github.com/mdn/helm-charts/blob/master/mysql/templates/pvc.yaml
#
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: icp-cloudant-backup-pvc
  annotations:
    # Don't delete the PVC via helm delete.
    "helm.sh/resource-policy": keep
  labels:
    app: icp-cloudant-backup
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
