apiVersion: batch/v1
kind: Job
metadata:
  name: icp-cloudant-backup
spec:
  template:
    spec:
      containers:
      - name: icp-cloudant-backup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["./cloudant-backup.sh", "--help"]
      restartPolicy: Never
  backoffLimit: {{ .Values.job.backoffLimit }}
