# See article on Kubernetes cronjob: https://chrisshort.net/kubernetes-cron-jobs/
# For cronjob schedule string just search the Internet for the schdule
# you are interested in, e.g,. cron job every 12 hours
# NOTE: Kubernetes uses UTC time for scheduling.

# Args common to backup, cleanup, etc
common:
  args:
    dbhost: cloudantdb.kube-system
    backupHome: /data/backups

backup:
  # cloudant-backup.sh command args
  args:
    exclude: "metrics metrics_app"
  cronjob:
    # Every noon, midnight (UTC): "0 */12 * * *"
    # Every hour: "0 * * * *"
    schedule: "0 * * * *"

cleanup:
  args:
    # Use retain to specify the number of backups to retain.
    retain: 3
  cronjob:
    # Every noon, midnight (UTC)
    schedule: "0 */12 * * *"


## Persist data to a persistent volume
persistence:
  # If the PVC has already been created then set pvc_exists to true.
  # TODO: Investigate way to inject detection of the PVC at deployment.
  pvc_exists: true
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass:
  accessMode: ReadWriteOnce
  size: 5Gi

replicaCount: 1

image:
  pullPolicy: Always
  tag: latest
  repository: mycluster.icp:8500/default/ibmcase/icp-cloudant-backup

# TBD: Run icp-cloudant-backup on one of the master nodes.
nodeSelector:
  role: master

job:
  backoffLimit: 3
