apiVersion: batch/v1
kind: Job
metadata:
  name: icp-cloudant-backup
spec:
  template:
    spec:
      containers:
      - name: icp-cloudant-backup
        image: "patrocinio/icp-backup-cloudant-backup:latest"
        command: ["/cloudant-backup.sh"]
      restartPolicy: Never
  backoffLimit: 3
